from enum import Enum

class PageType(str, Enum):
    NATIVE_TEXT = "NATIVE_TEXT"
    SCANNED_IMAGE = "SCANNED_IMAGE"
    MIXED = "MIXED"
    NATIVE_TEXT_LOW_QUALITY = "NATIVE_TEXT_LOW_QUALITY"
    IMAGE_ONLY = "IMAGE_ONLY"
    TABLE_HEAVY = "TABLE_HEAVY"
    DIAGRAM_HEAVY = "DIAGRAM_HEAVY"
